seed_everything: 2024

trainer:
  deterministic: True
  max_epochs: 100
  precision: 32
  num_sanity_val_steps: 0
  default_root_dir: ./ # training logs will be saved at `./lightning_logs`

model:
  network: CIFAR10DVSVGG
  T: 10
  neuron_type: SJLIF
  spike_compressor: NullSpikeCompressor
  decay_lambda: 0.25
  learning_rate: 0.1
  momentum: 0.9
  l2_factor: 5e-4
  lomo: False
  loss: tet


data:
  data_dir: /export/home/data_allenyolk/CIFAR10DVS
  T: 10
  batch_size: 32
  num_workers: 4
