seed_everything: 2024

trainer:
  deterministic: True
  max_epochs: 200
  precision: 32
  num_sanity_val_steps: 0
  default_root_dir: ./ # training logs will be saved at `./lightning_logs`

model:
  network: GCSpikformer
  neuron_type: SJLIF
  compress_x: True
  level: 0
  T: 4
  learning_rate: 0.001
  l2_factor: 5e-2
  smoothing: 0.1
  lomo: False


data:
  data_dir: /export/home/data_allenyolk/ImageNet0_03125
  cache_dataset: False
  batch_size: 32
  num_workers: 4
  for_model: transformer
