seed_everything: 2024

trainer:
  deterministic: True
  max_epochs: 100
  precision: 32
  num_sanity_val_steps: 0
  default_root_dir: ./ # training logs will be saved at `./lightning_logs`

model:
  network: PLIFSFNN
  spike_compressor: NullSpikeCompressor


data:
  data_dir: /export/home/data_allenyolk/SHD
  dt: 10
  batch_size: 128
  num_workers: 4
