seed_everything: 2024

trainer:
  max_epochs: 320
  precision: 32
  num_sanity_val_steps: 0
  default_root_dir: ./ # training logs will be saved at `./lightning_logs`

model:
  network: SEWResNet34
  neuron_type: SJLIF
  T: 4
  spike_compressor: NullSpikeCompressor
  learning_rate: 0.1
  momentum: 0.9
  loss: tet
  lomo: False


data:
  data_dir: /export/home/data_allenyolk/ImageNet0_03125
  cache_dataset: False
  batch_size: 32
  num_workers: 4
  for_model: sew
